on: 
  push: 
    branches:
      - master

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # The flutter action needs java so include it
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # Include the flutter action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # Get flutter packages
      - run: flutter pub get
      # Check for any formatting issues in code
      # - run: flutter format --set-exit-if-changed .
      # Statically analyze the Dart code for any errors
      - run: flutter analyze .
      # Build :D
      - run: flutter build apk --split-per-abi
      - run: mkdir build/app/outputs/apk/release
      - uses: actions/upload-artifact@v1
        with:
          # Name of the command/step.
          name: release-apk
          # Path to the release apk.
          path: build/app/outputs/apk/release/app-release.apk